FROM node:12.16.3-alpine3.9
ENV NODE_ENV=dev
# ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /tini
# RUN chmod +x /tini
RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app
USER node
COPY --chown=node:node package*.json ./

# The following line was commented due to the unknow error on DEV build
# RUN npm install --only=development
RUN npm install

COPY --chown=node:node . .
CMD [ "npm", "start" ]